### ISSUE TITLE
Make page look more fancier

### ISSUE THREAD

**Issue by rezemoe** [TTTaevas/OMT-Staff-Credits#3]
- [x] Apply different font (Torus Regular & Bold seems like the best option imo)
- [x] Apply different card design
> maybe like this? if yes, even tabling isn't needed anymore ( #2 )
![maybe this](https://user-images.githubusercontent.com/13962537/116820881-bb3e6180-ab90-11eb-9447-00e07ad80c70.png)

**Comment by TTTaevas** [comment]
Yes, definitely
Re-open the issue if you think readjustments should be made
