### ISSUE TITLE
Make card expansion more fancier

### ISSUE THREAD

**Issue by rezemoe** [TTTaevas/OMT-Staff-Credits#4]
![FANCYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY](https://user-images.githubusercontent.com/13962537/116888881-67418480-ac45-11eb-96c6-c109e96525b8.png)

**Comment by TTTaevas** [comment]
Oh my god, actual design genius, wtf
Thank you very much for those ideas

**Comment by TTTaevas** [comment]
e680325f64a9f71bd789224c3160007008c61633 alongside the previous commits should do the trick
