### ISSUE TITLE
Match role colors to be in the same scheme as whole website's design

### ISSUE THREAD

**Issue by rezemoe** [TTTaevas/OMT-Staff-Credits#5]
Colors applied by @AcezukyRO in https://github.com/TTTaevas/OMT-Staff-Credits/commit/b0fc35614996bcb307ea48fcbd947d4fa9428880 are not fitting the whole colorscheme of website

(tbf color madness is something i don't like so i would've just limited it to the same color on every role, but i don't think you intend it to use like that here so YEP)

**Comment by TTTaevas** [comment]
@lmnyx Do you have an opinion on 3183e1a802024123dae85774c246f39bccb74765?

**Comment by rezemoe** [comment]
Seems too bold, maybe `2px` or `2.5px` would be fine, also increasing the padding left & right would be nice.

**Comment by TTTaevas** [comment]
Reducing border thickness seems like a bad idea to me
Increasing padding was a good idea though
Thanks for all the feedback! :3
